/**
 * T1.4: Self-Improving Skills System
 * 
 * Integrates with the learning-engine to:
 * 1. Extract execution patterns from logs
 * 2. Generate skill documents (agentskills.io compatible)
 * 3. Match user requests to relevant skills
 * 4. Refine skills over time
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

// ---- Types ----

export interface Skill {
  id: string;
  name: string;
  description: string;
  category: string;
  keywords: string[];
  pattern: string;
  steps: SkillStep[];
  examples: SkillExample[];
  version: string;
  created_at: string;
  updated_at: string;
  execution_count: number;
  success_rate: number;
}

export interface SkillStep {
  order: number;
  action: string;
  tool?: string;
  description: string;
}

export interface SkillExample {
  input: string;
  output: string;
  description: string;
}

export interface ExecutionRecord {
  workflowId: string;
  taskText: string;
  steps: string[];
  success: boolean;
  durationMs: number;
  timestamp: string;
}

// ---- Skill Manager ----

export class SkillManager {
  private skillsDir: string;

  constructor(skillsDir?: string) {
    this.skillsDir = skillsDir || path.resolve(process.cwd(), '..', 'skills');
    this.ensureDir();
  }

  private ensureDir(): void {
    if (!fs.existsSync(this.skillsDir)) {
      fs.mkdirSync(this.skillsDir, { recursive: true });
    }
  }

  /** List all stored skills */
  listSkills(): Skill[] {
    const skills: Skill[] = [];
    if (!fs.existsSync(this.skillsDir)) return skills;

    for (const file of fs.readdirSync(this.skillsDir)) {
      if (file.endsWith('.json') || file.endsWith('.skill.md')) {
        try {
          const content = fs.readFileSync(path.join(this.skillsDir, file), 'utf-8');
          if (file.endsWith('.json')) {
            skills.push(JSON.parse(content));
          } else {
            // Parse markdown skill format (agentskills.io compatible)
            const skill = this.parseMarkdownSkill(content, file);
            if (skill) skills.push(skill);
          }
        } catch { /* skip unparseable skills */ }
      }
    }
    return skills;
  }

  /** Find skills matching a user request */
  findMatchingSkills(query: string): Skill[] {
    const q = query.toLowerCase();
    return this.listSkills().filter((s) =>
      s.keywords.some((k) => q.includes(k.toLowerCase())) ||
      s.description.toLowerCase().includes(q) ||
      s.name.toLowerCase().includes(q)
    );
  }

  /** Generate a skill from an execution record */
  generateSkill(record: ExecutionRecord): Skill {
    const name = this.makeSkillName(record.taskText);
    const skill: Skill = {
      id: `skill_${Date.now()}`,
      name,
      description: `Automated skill: ${record.taskText.slice(0, 100)}`,
      category: 'auto_generated',
      keywords: this.extractKeywords(record.taskText),
      pattern: record.steps.join(' → '),
      steps: record.steps.map((step, i) => ({
        order: i + 1,
        action: step,
        description: `Step ${i + 1}: ${step}`,
      })),
      examples: [{
        input: record.taskText,
        output: `Completed in ${record.durationMs}ms`,
        description: record.taskText,
      }],
      version: '1.0.0',
      created_at: record.timestamp,
      updated_at: record.timestamp,
      execution_count: 1,
      success_rate: record.success ? 1.0 : 0.0,
    };

    this.saveSkill(skill);
    return skill;
  }

  /** Save skill to disk */
  saveSkill(skill: Skill): void {
    const filePath = path.join(this.skillsDir, `${skill.id}.json`);
    fs.writeFileSync(filePath, JSON.stringify(skill, null, 2), 'utf-8');
  }

  /** Export skill in markdown format (agentskills.io compatible) */
  exportToMarkdown(skill: Skill): string {
    return `# ${skill.name}

${skill.description}

**Category**: ${skill.category}
**Version**: ${skill.version}
**Pattern**: ${skill.pattern}

## Keywords
${skill.keywords.map((k) => `- ${k}`).join('\n')}

## Steps
${skill.steps.map((s) => `${s.order}. **${s.action}** - ${s.description}`).join('\n')}

## Examples
${skill.examples.map((e) => `### ${e.description}\n- Input: \`${e.input}\`\n- Output: \`${e.output}\``).join('\n')}

---
*Auto-generated by MemFlow Skill System*
`;
  }

  private makeSkillName(text: string): string {
    const cleaned = text.replace(/[^a-zA-Z0-9\s]/g, '').trim();
    const words = cleaned.split(/\s+/).slice(0, 5);
    return words.map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
  }

  private extractKeywords(text: string): string[] {
    const stopWords = new Set(['the', 'a', 'an', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'and', 'or', 'is', 'are', 'was', 'were']);
    return text
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .split(/\s+/)
      .filter((w) => w.length > 3 && !stopWords.has(w))
      .slice(0, 10);
  }

  private parseMarkdownSkill(content: string, filename: string): Skill | null {
    try {
      const name = filename.replace(/\.skill\.md$/, '');
      const descMatch = content.match(/^(.+)$/m);
      return {
        id: filename,
        name,
        description: descMatch?.[1] || 'Parsed skill',
        category: 'parsed',
        keywords: [],
        pattern: '',
        steps: [],
        examples: [],
        version: '1.0.0',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        execution_count: 0,
        success_rate: 0,
      };
    } catch {
      return null;
    }
  }
}

export default SkillManager;
