apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memflow.fullname" . }}-secrets
  labels:
    {{- include "memflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  executor-api-key: {{ .Values.config.executorApiKey | default (randAlphaNum 32) | quote }}
  openai-api-key: {{ .Values.config.openaiApiKey | quote }}
